version: '2'
services:
  yqbot:
    image: "clarkzjw/yuequnbot:latest"
    env_file: .envfile
    restart: always
    command: python /yqbot/app/app.py
  consumer:
    image: "clarkzjw/yuequnbot:latest"
    env_file: .envfile
    restart: always
    command: python /yqbot/app/broker/rabbitmq/consumer.py
